language: ruby
services:
  - docker
before_install:
  - docker-compose up -d
  - docker ps
  - docker-compose run app rake db:create
  - docker-compose run app rake db:migrate
script:
  
after_install:
  - docker-compose stop
